version: '3.9'

services:
  database:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '258697'
      MYSQL_DATABASE: 'meus_links'
    ports:
      - '3306:3306'
